const SBD = 'SBD'
const STEEM = 'STEEM'
const SP = 'SP'
const VESTS = 'VESTS'
const RPC_NODE = { url: 'https://api.steemit.com' }
const HARDFORK = 20

const STEEM_100_PERCENT = 10000
const STEEM_VOTE_REGENERATION_SECONDS = 432000 //5 DAYS

export default {
  SBD: SBD,
  STEEM: STEEM,
  SP: SP,
  VESTS: VESTS,
  RPC_NODE: RPC_NODE,
  
  STEEM_100_PERCENT: STEEM_100_PERCENT,
  STEEM_VOTE_REGENERATION_SECONDS: STEEM_VOTE_REGENERATION_SECONDS,
}
