const SBD = "EUR";
const STEEM = "EFTG";
const SP = "SP";
const VESTS = "VESTS";
const RPC_NODE = { url: "https://api.blkcc.xyz" };
const IMAGE_HOSTER = { url: "https://cdn.blkcc.xyz" };
const EXPLORER = { url: "http://explorer.blkcc.xyz/#" };
const HARDFORK = 19

const STEEM_ADDRESS_PREFIX = "EUR";
const STEEM_100_PERCENT = 10000;
const STEEM_VOTE_REGENERATION_SECONDS = 5 * 24 * 60 * 60;
const STEEM_INFLATION_RATE_START_PERCENT = 978;
const STEEM_INFLATION_NARROWING_PERIOD = 250000;
const STEEM_INFLATION_RATE_STOP_PERCENT = 95;
const STEEM_BLOCKS_PER_YEAR = (365 * 24 * 60 * 60) / 3;
const STEEM_BLOCKS_PER_DAY = (24 * 60 * 60) / 3;
const STEEM_SBD_START_PERCENT = 900;
const STEEM_SBD_STOP_PERCENT = 1000;

const MAP = {
  TOP_WITNESSES: 30,
  INI_POS : [50.5, 15], //latitude, longitude
  INI_ZOOM : 4 ,
}

const APP_VERSION = "pulsar/0.0.2";

export default {
  SBD: SBD,
  STEEM: STEEM,
  SP: SP,
  VESTS: VESTS,
  RPC_NODE: RPC_NODE,
  IMAGE_HOSTER: IMAGE_HOSTER,
  EXPLORER: EXPLORER,
  HARDFORK: HARDFORK,

  STEEM_ADDRESS_PREFIX: STEEM_ADDRESS_PREFIX,
  STEEM_100_PERCENT: STEEM_100_PERCENT,
  STEEM_VOTE_REGENERATION_SECONDS: STEEM_VOTE_REGENERATION_SECONDS,
  STEEM_INFLATION_RATE_START_PERCENT: STEEM_INFLATION_RATE_START_PERCENT,
  STEEM_INFLATION_NARROWING_PERIOD: STEEM_INFLATION_NARROWING_PERIOD,
  STEEM_INFLATION_RATE_STOP_PERCENT: STEEM_INFLATION_RATE_STOP_PERCENT,
  STEEM_BLOCKS_PER_YEAR: STEEM_BLOCKS_PER_YEAR,
  STEEM_BLOCKS_PER_DAY: STEEM_BLOCKS_PER_DAY,
  STEEM_SBD_START_PERCENT: STEEM_SBD_START_PERCENT,
  STEEM_SBD_STOP_PERCENT: STEEM_SBD_STOP_PERCENT,
  
  MAP:MAP,
  
  APP_VERSION: APP_VERSION,
};
